spring.application.name=SpringAiDemo
server.port=8082

spring.ai.openai.api-key=${GROK_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-20b